name: PETA Cron Job

on:
  #schedule:
  #  - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo on main branch
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # actions/checkout@v7.0.0
      with:
        ref: main

    - name: Setup Bun
      uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Fetch PETA Data and Save
      run: bun ${{ github.workspace }}/.github/scripts/peta-cron.js

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add peta_cruelty_free.json
        git commit -m "Update peta_cruelty_free.json" || echo "No changes to commit"
        git push origin main --force
